### ISSUE TITLE
Retain messages won't make sense for events

### ISSUE THREAD

**Issue by spamik** [OctoPrint/OctoPrint-MQTT#76]
I believe that events messages should be send without retain flag even if it's configured in settings. Now all of them are sent with retain and this setting is turned on by default.

Maybe it will have some sense when events will have some common topic but when each event has it's own topic, newly connected broker receive a lot of messages with opposite meaning (like Client Opened and Client Disconnected, Shutdown event when octoprint is running and so on).

**Comment by Kllrv** [comment]
I agree, and furthermore all the different topics being sent at once to new clients makes no sense. It's very hard to make anything react to different events in a meaningful manner like this.

**Comment by smurfix** [comment]
Well, that's a question of event design. Right now we have events (like PrintDone or UserLoggedIn) which make no sense to retain (the fact that I last paused a print two months ago is not interesting), but others (temperature, Z Layer, FirmwareData) are more like a state and thus should have Retain set.

My idea would be to move the State-like events to a separate subtopic. Also, we should use "clean" stateful topics to reflect some events. I.e. instead of PrintStarted and PrintStopped events (you need to compare timestamps to extract meaning from them when you start up your client, ugh!) there should be a PrinterState that contains state=printing file=foobar.gcode, or state=finished, state=halted, state=paused.

Side benefit, that way the printer state can be reflected in Home Assistant (or whatever) directly, instead of depending on custom code that does event filtering and timestamp comparison, and which will break if somebody decides to add a new state.
